### ISSUE TITLE
Fits.version() broken resource link in Debian package

### ISSUE THREAD

**Issue by attipaci** [nom-tam-fits/nom-tam-fits#132]
When `fits.jar` is installed via the Debian package (into `/usr/share/java`, v. 1.15.2), it has a broken resource link to the version information. Trying to call ```Fits.version()``` throws a NullPointerException:

    Exception in thread "main" java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.Properties.load(Properties.java:397)
	at nom.tam.fits.Fits.version(Fits.java:380)

As such, the 1.15.2 deployment is currently broken.

**Comment by attipaci** [comment]
I posted this, but it does not belong here. It really is something for the maintainers of the Debian package.
