### ISSUE TITLE
Rice Compression regression of 8-bit and 16-bit images in 1.18.0-rc6

### ISSUE THREAD

**Issue by keastrid** [nom-tam-fits/nom-tam-fits#460]
There seems to be a regression with the compression of 16bit integer images in 1.18. I am unsure which commit is at issue.

Attempting to compress a 16bit image HDU with RICE_1 produces an invalid file. Attempting to open it in fv or with nom.tam produces an exception.

This occurs with every 16bit file I have tried, attached is a simple test one. [16bitTest.zip](https://github.com/nom-tam-fits/nom-tam-fits/files/12032956/16bitTest.zip)

The HDUs are incrementally written to the file, first adding a null HDU, then the compressed image HDU. Using GZIP_2 for floating point images in this same code path does not have this issue.

Nom.tam error when reading:
```
java.lang.IllegalStateException: could not process tile
	at nom.tam.image.tile.operation.AbstractTileOperation.waitForResult(AbstractTileOperation.java:131)
	at nom.tam.image.compression.tile.TiledImageCompressionOperation.processAllTiles(TiledImageCompressionOperation.java:398)
	at nom.tam.image.compression.tile.TiledImageCompressionOperation.decompress(TiledImageCompressionOperation.java:162)
	at nom.tam.image.compression.hdu.CompressedImageData.getUncompressedData(CompressedImageData.java:111)
	at nom.tam.image.compression.hdu.CompressedImageHDU.getUncompressedData(CompressedImageHDU.java:408)
	at nom.tam.image.compression.hdu.CompressedImageHDU.asImageHDU(CompressedImageHDU.java:202)
	at ij.plugin.FITS_Reader.getCompressedImageData(FITS_Reader.java:345)
	at ij.plugin.FITS_Reader.run(FITS_Reader.java:127)
	at ij.IJ.runPlugIn(IJ.java:215)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.io.Opener.openImage(Opener.java:368)
	at ij.io.Opener.openImage(Opener.java:262)
	at ij.io.Opener.open(Opener.java:125)
	at ij.io.Opener.openAndAddToRecent(Opener.java:332)
	at ij.plugin.DragAndDrop.openFile(DragAndDrop.java:207)
	at ij.plugin.DragAndDrop.run(DragAndDrop.java:173)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: could not decompress public nom.tam.fits.compression.algorithm.rice.RiceCompressor$ShortRiceCompressor(nom.tam.fits.compression.algorithm.rice.RiceCompressOption)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at nom.tam.image.tile.operation.AbstractTileOperation.waitForResult(AbstractTileOperation.java:129)
	... 16 more
Caused by: java.lang.IllegalStateException: could not decompress public nom.tam.fits.compression.algorithm.rice.RiceCompressor$ShortRiceCompressor(nom.tam.fits.compression.algorithm.rice.RiceCompressOption)
	at nom.tam.fits.compression.provider.CompressorProvider$TileCompressorControl.decompress(CompressorProvider.java:127)
	at nom.tam.image.compression.tile.TileDecompressor.decompress(TileDecompressor.java:80)
	at nom.tam.image.compression.tile.TileDecompressor.run(TileDecompressor.java:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more
Caused by: java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:699)
	at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:165)
	at nom.tam.fits.compression.algorithm.rice.RiceCompressor.decompressBuffer(RiceCompressor.java:477)
	at nom.tam.fits.compression.algorithm.rice.RiceCompressor$ShortRiceCompressor.decompress(RiceCompressor.java:156)
	at nom.tam.fits.compression.algorithm.rice.RiceCompressor$ShortRiceCompressor.decompress(RiceCompressor.java:138)
	at nom.tam.fits.compression.provider.CompressorProvider$TileCompressorControl.decompress(CompressorProvider.java:125)
	... 7 more

```

**Comment by attipaci** [comment]
Thanks @keastrid. We'll certainly have this fixed before the release. I'll try to bracket the commit. Hopefully it's something trivial...

**Comment by keastrid** [comment]
I'll see if I can find the commit, but the history is a bit messed up on our end.

**Comment by attipaci** [comment]
Well see what you can do. Thanks for trying. Another thing to check is how the good files differ from the bad ones. Are the headers the same? Is the binary data totally different, or just truncated?

**Comment by keastrid** [comment]
8bit images are also affected.
[8bit original and broken](https://github.com/nom-tam-fits/nom-tam-fits/files/12033846/issue.zip)

HCompress with 16bit images seems to be working.

Hmm, the broken HDU's header has this oddity: `NAXIS1  = '8       '           / size of the n'th axis    ` (notice the quotes)

**Comment by keastrid** [comment]
That is, the header nom.tam will dump for the compressed hdu when reading back the image

**Comment by attipaci** [comment]
I also did some checking. I think naxis1 = 8 is OK (a single column with two 32-bit heap pointers). However, the BYTEPIX is written as 4, all the type -- but should be 2 for shorts and 1 for byte. So, I think the problem is with that....

**Comment by keastrid** [comment]
Possibly unrelated, HCompress works when reading for nom.tam, but fv cannot open the image - cfitsio error 415 ([NO_COMPRESSED_TILE](https://www2.mpia-hd.mpg.de/~mathar/progs/cfitsio_api/fitsio_8h.html#ad10836e55f52a039f04bd730c8371bea)).

**Comment by keastrid** [comment]
> I also did some checking. I think naxis1 = 8 is OK (a single column with two 32-bit heap pointers). However, the BYTEPIX is written as 4, all the type -- but should be 2 for shorts and 1 for byte. So, I think the problem is with that....
> 
> Indeed. If I just change ZVAL2 to 2 after writing the compressed file, it works!

That's interesting... at least there's a chance the files can be fixed then.

**Comment by keastrid** [comment]
Trying myself with the compressed 16bit image, I get:
```
nom.tam.fits.FitsException: Error decoding heap area at offset=538976288, size=538976322 (size 296418): null
	at nom.tam.fits.FitsHeap.getData(FitsHeap.java:122)
	at nom.tam.fits.BinaryTable.readHeap(BinaryTable.java:3562)
	at nom.tam.fits.BinaryTable.getFromHeap(BinaryTable.java:3205)
	at nom.tam.fits.BinaryTable.getElement(BinaryTable.java:2357)
	at nom.tam.fits.BinaryTable.getElement(BinaryTable.java:2330)
	at nom.tam.fits.BinaryTable.getColumn(BinaryTable.java:2115)
	at nom.tam.image.compression.tile.TiledImageCompressionOperation.getNullableColumn(TiledImageCompressionOperation.java:385)
	at nom.tam.image.compression.tile.TiledImageCompressionOperation.read(TiledImageCompressionOperation.java:267)
	at nom.tam.image.compression.hdu.CompressedImageData.getUncompressedData(CompressedImageData.java:110)
	at nom.tam.image.compression.hdu.CompressedImageHDU.getUncompressedData(CompressedImageHDU.java:408)
	at nom.tam.image.compression.hdu.CompressedImageHDU.asImageHDU(CompressedImageHDU.java:202)
	at ij.plugin.FITS_Reader.getCompressedImageData(FITS_Reader.java:347)
	at ij.plugin.FITS_Reader.run(FITS_Reader.java:127)
	at ij.IJ.runPlugIn(IJ.java:215)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.io.Opener.openImage(Opener.java:368)
	at ij.io.Opener.openImage(Opener.java:262)
	at ij.io.Opener.open(Opener.java:125)
	at ij.io.Opener.openAndAddToRecent(Opener.java:332)
	at ij.plugin.DragAndDrop.openFile(DragAndDrop.java:207)
	at ij.plugin.DragAndDrop.run(DragAndDrop.java:173)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.EOFException
	at nom.tam.util.InputDecoder.readFully(InputDecoder.java:178)
	at nom.tam.util.FitsDecoder.readArray(FitsDecoder.java:510)
	at nom.tam.util.InputDecoder.readArrayFully(InputDecoder.java:200)
	at nom.tam.fits.FitsHeap.getData(FitsHeap.java:119)
	... 21 more

```

**Comment by keastrid** [comment]
Setting bytepix before compressing seems to fix it for both 16 and 8bit options.

**Comment by attipaci** [comment]
Yes, I will make sure to fix it so that it has an automatic default that works...

**Comment by keastrid** [comment]
No worries, it also went unnoticed on our end.
I think there's some redundancy in the headers, so maybe it can be check when written?

**Comment by attipaci** [comment]
@keastrid, Please check out PR #461 with the proposed fix. It actually improves on the older setup with more robust way of processing BYTEPIX and BLOCKSIZE -- both automatically and when set explicitly, and includes validating these settings to ensure they abide by the FITS standard or else throwing an `IllegalArgumentException`...

**Comment by attipaci** [comment]
> Possibly unrelated, HCompress works when reading for nom.tam, but fv cannot open the image - cfitsio error 415 ([NO_COMPRESSED_TILE](https://www2.mpia-hd.mpg.de/~mathar/progs/cfitsio_api/fitsio_8h.html#ad10836e55f52a039f04bd730c8371bea)).

This problem also seems to be cured. I've been able to open HCompressed images with __fv__ just fine.

**Comment by attipaci** [comment]
> Possibly unrelated, HCompress works when reading for nom.tam, but fv cannot open the image - cfitsio error 415 ([NO_COMPRESSED_TILE](https://www2.mpia-hd.mpg.de/~mathar/progs/cfitsio_api/fitsio_8h.html#ad10836e55f52a039f04bd730c8371bea)).

This problem seems to be cured also. I have been able to open HCompressed files with __fv__ and the image is also what went into it.
