### ISSUE TITLE
BinaryTable.addColumn(ColumnDesc) uninitialized fileSize

### ISSUE THREAD

**Issue by attipaci** [nom-tam-fits/nom-tam-fits#551]
### Discussed in https://github.com/nom-tam-fits/nom-tam-fits/discussions/550

<div type='discussions-op-text'>

<sup>Originally posted by **keastrid** February 14, 2024</sup>
I'm having trouble creating compressed binary tables with nom.tam 1.19.0. Writing uncompressed tables and compressed images both work.

Attempting to read individual HDUs appears to work without issue, but trying to read all of them with `Fits#read` throws the following exception:
```
Feb 14, 2024 8:18:47 PM nom.tam.fits.Header forceEOF
WARNING: Junk detected where header was expected to start: at 8640
nom.tam.fits.TruncatedFileException: Got only 8 of 80 bytes expected for a header card
	at nom.tam.fits.HeaderCard.readRecord(HeaderCard.java:1776)
	at nom.tam.fits.HeaderCard.readOneHeaderLine(HeaderCard.java:1798)
	at nom.tam.fits.HeaderCard.<init>(HeaderCard.java:204)
	at nom.tam.fits.Header.read(Header.java:1977)
	at nom.tam.fits.Header.readHeader(Header.java:244)
	at nom.tam.fits.Fits.readHDU(Fits.java:1171)
	at nom.tam.fits.Fits.readToEnd(Fits.java:1206)
	at nom.tam.fits.Fits.read(Fits.java:1116)
	at ij.plugin.FITS_Writer.main(FITS_Writer.java:574)
```

Trying to unpack the file with funpack gives the following error:
```
Error processing file: test.tbl.fits.fz
  in HDU number 1

FITSIO status = 241: row width not = field widths
NAXIS1 = 0 is not equal to the sum of column widths: 8
Failed to move to HDU number 2 (ffmahd).
Input file is unchanged.
```

I've been working with incremental writing, but the issue can be reproduced with the "normal" writing method as I have done here.

A simplified reproduction case I have created:
```java
try {
	Path outPath = Path.of(path);

	System.out.println(outPath);

	// Saving canceled
	if (outPath.getParent() == null) {
		return;
	}

	Files.createDirectories(outPath.getParent());

	var fits = new Fits();

	// Write primary header
	var nullHdu = Fits.makeHDU((Object) null);
	nullHdu.addValue(EXTEND, true);
	nullHdu.addValue("AIJ_TBL", true, "AIJ Measurements table and plotcfg");
	fits.addHDU(nullHdu);

	BinaryTable table = new BinaryTable();

	table.addColumn(new double[]{1, 2, 3, 4, 5, 6, 7, 8});
	table.defragment();

	var hdu = table.toHDU();

	if (true) {
		var compressedHdu = CompressedTableHDU.fromBinaryTableHDU(hdu, 0); // also tried -1 and 4
		compressedHdu.compress();
		hdu = compressedHdu;
	}

	fits.addHDU(hdu);

	fits.write(outPath.toFile());
	fits.close();
} catch (Exception e) {
	e.printStackTrace();
}

// try custom read
try {
	var fits = new Fits(path);
	/*System.out.println(fits.getHDU(0)); // works
	var h = fits.getHDU(1);
	if (h instanceof CompressedTableHDU c) { //works
		var t = c.asBinaryTableHDU();
		if (t.getColumn(0) instanceof double[] d) {
			System.out.println(Arrays.toString(d)); //prints correct values
		}
	}*/

	fits.read(); //exception

} catch (Exception e) {
	e.printStackTrace();
}
```

An example of the output is [here](https://github.com/nom-tam-fits/nom-tam-fits/files/14290291/test.tbl.fits.fz.zip)</div>

**Comment by attipaci** [comment]
The issue seems to originate in `BinaryTable.addColumn(ColumnDesc)` not initializing the file size of column entries, hence NAXIS1 is written as 0.
