### ISSUE TITLE
Error degragmenting table with `byte[]` column

### ISSUE THREAD

**Issue by keastrid** [nom-tam-fits/nom-tam-fits#580]
Using nom.tam 1.19.1-pre.1 [ee3dd0b](https://github.com/nom-tam-fits/nom-tam-fits/commit/ee3dd0bcb6d53384422bd4a3910955e4a91b5cc6).

I am attempting to work around funpack's inability to deal with uncompressed columns and lack of compression of strings by converting them into UTF-8 encoded byte arrays such that the column's type is `byte[][]`.

This table is built column-by-column, but when I attempt to defagment the table I get the follow exception:
```stacktrace
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 16388 out of bounds for byte[16384]
	at java.base/java.lang.System.arraycopy(Native Method)
	at nom.tam.fits.FitsHeap.copyFrom(FitsHeap.java:196)
	at nom.tam.fits.BinaryTable.defragment(BinaryTable.java:3977)
```

The number of rows in this instance is `15768`, I have yet to produce something more minimal to reproduce this.

When not defragmenting, the table is successfully written and can be funpacked, as well as nom.tam reading both the compressed and uncompressed forms.

Excerpt of the code used to produce the exception:
```java
BinaryTable table = new BinaryTable();

if (resultsTable.hasRowLabels()) {
	// We cannot use strings directly as funpack does not allow compression for them
	// and cannot handle NOCOMPRESS columns due to being broken
	//table.addStringColumn(resultsTable.getColumnAsStrings("Label"));
	var a = Arrays.stream(resultsTable.getColumnAsStrings("Label"))
			.map(s -> s.getBytes(StandardCharsets.UTF_8)).toArray(byte[][]::new);
	System.out.println(a.length);
	table.addColumn(a);
}

for (int col = 0; col <= resultsTable.getLastColumn(); col++) {
	table.addColumn(resultsTable.getColumnAsDoubles(col));
}
table.defragment();
```

Attached is the compressed non-defagmented table
[test_measurements.fits.fz.zip](https://github.com/nom-tam-fits/nom-tam-fits/files/14624213/test_measurements.fits.fz.zip)

**Comment by keastrid** [comment]
Thanks, seems to have fixed it!
