### ISSUE TITLE
Problem handling header cards with "almost" long string

### ISSUE THREAD

**Issue by JonCook** [nom-tam-fits/nom-tam-fits#67]
I made a simple test harness.

```java
public static void main(String[] args) throws FitsException, IOException {
    ArrayList<Header> headers = getHeaders("bad.fits");
    System.out.println(headers.size());
}
```

```java
private static ArrayList<Header> getHeaders(String filename) throws IOException, FitsException {
        ArrayList<Header> list = new ArrayList<Header>();
        try (Fits f = new Fits(filename)) {
            BasicHDU<?> readHDU = f.readHDU();
            while (readHDU != null) {
                f.deleteHDU(0);
                list.add(readHDU.getHeader());
                readHDU = f.readHDU();
            }
        }
        return list;
    }
```

When I run this I get.
```
Exception in thread "main" java.io.IOException: Invalid FITS Header
    at nom.tam.fits.Header.read(Header.java:1341)
    at nom.tam.fits.Header.readHeader(Header.java:115)
    at nom.tam.fits.Fits.readHDU(Fits.java:647)
    at herschel.ia.io.fits.FitsTest.getHeaders(FitsTest.java:44)
    at herschel.ia.io.fits.FitsTest.main(FitsTest.java:33)
Caused by: java.io.IOException: Not FITS format at 2800:
    at nom.tam.fits.Header.read(Header.java:1303)
    ... 4 more
```

I'm using one of the latest snapshots -
nom-tam-fits-1.14.0-20151227.142206-107.jar

Apparently the problem is the header card that is "almost" a long-sting, this is handled correctly but the position in the file is not set back to the correct position that's why he misses the next header by 80 bytes.

Thanks
Jon

**Comment by JonCook** [comment]
Unfortunately I can't attach the offending file as github doesn't support that type but you have a copy for a unit test.

**Comment by JonCook** [comment]
Shall I try tomorrow's snapshot? Thanks
