### ISSUE TITLE
Reading Fits fails with Invalid FITS Header IOException

### ISSUE THREAD

**Issue by JonCook** [nom-tam-fits/nom-tam-fits#73]
Given the following FITS file which I agree is a little strange but is valid. Trying to load the FITS file with the latest snapshot results in the following error:

```
File name:  16913-1.fits
                                           Run Number 18903
 
              fitsverify 4.16 (CFITSIO V3.320)              
              --------------------------------              
 

1 Header-Data Units in this file.
 
=================== HDU 1: Primary Array ===================
 
   1 | SIMPLE  =                    T / Java FITS: Tue Jan 19 14:50:37 CET 2016
   2 | BITPIX  =                   32 / bits per data value
   3 | NAXIS   =                    0 / number of axes
   4 | EXTEND  =                    T / May contain datasets
   5 | TIMESYS = 'UTC     '           / All dates are in UTC time
   6 | LONGSTRN= 'OGIP 1.0'           / The OGIP long string convention may be used.
   7 | COMMENT This FITS file may contain long string keyword values that are
   8 | COMMENT continued over multiple keywords.  This convention uses the  '&'
   9 | COMMENT character at the end of a string which is then continued
  10 | COMMENT on subsequent keywords whose name = 'CONTINUE'.
  11 |          ---------------Herschel FITS Data Generator---------------
  12 |          This product is generated by Herschel software.
  13 | HCSS____=                    5 / HCSS Fits Product Version
  14 |          -------------- Herschel Structure Data--------------------
  15 |          Following fields are private to the structure of the
  16 |          Java object this HDU is representing.
  17 | CLASS___= 'herschel.ia.dataset.Product' / java representation
  18 | INFO____= 'Unknown '
  19 |          -------------- Herschel Parameter Data--------------------
  20 |          All actual parameter names are converted to FITS compliant
  21 |          conventions. Note that the HIERARCH comments contain the
  22 |          appropriate key mapping
  23 | TYPE    = 'Unknown '           / Product Type Identification
  24 | CREATOR = 'Unknown '           / Generator of this product
  25 | DATE    = '2016-01-19T13:50:48.687000' / Creation date of this product
  26 | DESC    = 'Unknown '           / Name of this product
  27 | INSTRUME= 'Unknown '           / Instrument attached to this product
  28 | MODELNAM= 'Unknown '           / Model name attached to this product
  29 | DATE-OBS= '2016-01-19T13:50:48.687000' / Start date of this product
  30 | DATE_OBS= '2016-01-19T13:50:48.687000' / Start date of this product
  31 | DATE-END= '2016-01-19T13:50:48.687000' / End date of this product
  32 | FORMATV = '1.0     '           / Version of product format
  33 | META_0  = '&       '
  34 | CONTINUE '' / &
  35 | COMMENT Comment written when the proposal was technically evaluated
  36 | HIERARCH  key.TYPE= 'type    '
  37 | HIERARCH  key.CREATOR= 'creator'
  38 | HIERARCH  key.DATE= 'creationDate'
  39 | HIERARCH  key.DESC= 'description'
  40 | HIERARCH  key.INSTRUME= 'instrument'
  41 | HIERARCH  key.MODELNAM= 'modelName'
  42 | HIERARCH  key.DATE-OBS= 'startDate'
  43 | HIERARCH  key.DATE-END= 'endDate'
  44 | HIERARCH  key.FORMATV= 'formatVersion'
  45 | HIERARCH  key.META_0= 'test  '
  46 | END     
 
 46 header keywords
 
 Null data array; NAXIS = 0 
 
++++++++++++++++++++++ Error Summary  ++++++++++++++++++++++
 
 HDU#  Name (version)       Type             Warnings  Errors
 1                          Primary Array    0         0     
 
**** Verification found 0 warning(s) and 0 error(s). ****
```

```java
Exception in thread "main" java.io.IOException: Invalid FITS Header
	at herschel.ia.io.fits.FitsArchive.load(FitsArchive.java:431)
	at herschel.ia.io.fits.FitsArchive.load(FitsArchive.java:395)
	at herschel.ia.io.FitsTest.readFits(FitsTest.java:97)
	at herschel.ia.io.FitsTest.main(FitsTest.java:29)
Caused by: herschel.ia.io.ArchiveException: Invalid FITS Header
	at herschel.ia.io.fits.reader.ReadHduIterable.read(ReadHduIterable.java:90)
	at herschel.ia.io.fits.reader.ReadHduIterable.hasNext(ReadHduIterable.java:58)
	at herschel.ia.io.fits.reader.ConfigurableFitsHandler.handle(ConfigurableFitsHandler.java:208)
	at herschel.ia.io.fits.AbstractFitsReader.read(AbstractFitsReader.java:97)
	at herschel.ia.io.fits.AbstractFitsReader.read(AbstractFitsReader.java:75)
	at herschel.ia.io.fits.FitsArchive.load(FitsArchive.java:425)
	... 3 more
Caused by: java.io.IOException: Invalid FITS Header
	at nom.tam.fits.Header.read(Header.java:1340)
	at nom.tam.fits.Header.readHeader(Header.java:115)
	at nom.tam.fits.Fits.readHDU(Fits.java:645)
	at herschel.ia.io.fits.reader.ReadHduIterable.read(ReadHduIterable.java:80)
	... 8 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:210)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at nom.tam.fits.HeaderCard.longStringCard(HeaderCard.java:621)
	at nom.tam.fits.HeaderCard.extractValueCommentFromString(HeaderCard.java:499)
	at nom.tam.fits.HeaderCard.<init>(HeaderCard.java:259)
	at nom.tam.fits.Header.read(Header.java:1302)
	... 11 more
```

Trying to switch off FitsFactory.setLongStringsEnabled(false); has no effect because inside Header.java the LONGSTRN is detected. Ultimately the error occurs here:
private void longStringCard on line if (longValue.charAt(longValue.length() - 1) == '&') {

These are FITS files which were probably created a very long time ago but are in the system. I can provide the FITS if you wish for a unit test.

Thanks

**Comment by ritchieGitHub** [comment]
yes please provide the fits file. (If you need space you can make a pull request to https://github.com/nom-tam-fits/blackbox-images, there it will land anyway ;-) )

**Comment by JonCook** [comment]
I made a PR with the file. Thanks.

**Comment by ritchieGitHub** [comment]
fixed, please test it. I am delaying the 1.14.0 release till you have no more issues. So when possible test it today?

**Comment by JonCook** [comment]
Does today's snapshot nom-tam-fits-1.14.0-20160122.071356-140-sources.jar include this fix then? Or I need to wait? We are not using maven so I have to download the jars.

**Comment by ritchieGitHub** [comment]
yes, today's snapshot should fix all your reported issues. (excluding the not yet reported ;-) )

**Comment by ritchieGitHub** [comment]
I would recommend using maven, after a small initial learning period, it make your life so much easier!

**Comment by JonCook** [comment]
OK thanks. Yes I'm familiar with maven but unfortunately our project is not using it for the moment. I will try with the latest snapshot now. Thanks.

**Comment by JonCook** [comment]
The latest version fixes this. Thanks.
